### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by tranjamin**
Merge setup through to main. App has basic display functionality and connects to firebase services.

### CODE REVIEW

**Comment by tranjamin** [comment]
Requesting a review for an initial commit to the website. I'm not concerned at the moment that the site is incomplete, because I want to test that the app performs in production. Approve this merge request ("Add your review" -> "Review changes" on the right hand side) unless you have any grievous exceptions, but do leave comments for any suggestions. Most of the review is checking the site looks fine by opening the preview link above (https://uqrl-website--pr3-develop-m7ad2lkg.web.app/). You can also review the code itself when you add your review, but because it is a massive merge it's not really practical

**Review by SrikrishnaBhat — APPROVED** [review]
Changes are fine for an initial commit. Looking at the the preview the lack of control on the spinning cube can get annoying, need a mouse based control of the rotation and a label mentioning the page or tab it needs to be sent to.

**Comment by tranjamin** [comment]
Those two things are on my to do list yep

**Review by uq-realitylabs — APPROVED** [review]

**Review by tranjamin — COMMENTED** [review]
Approved on behalf of Srikrishna (apparently not part of the org yet)

**Pull request merged**
